[package]
name = "jesse/roblox-dsac-boilerplate"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.5.3"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@1.5.0"
Janitor = "howmanysmall/janitor@1.15.6"
t = "shanebutt/t@1.3.1"
Timer = "sleitnick/timer@1.1.2"
replica = "luarook/replica@0.2.2"