[package]
name = "suit-up-repos/roblox-dsac-boilerplate"
description = "a boilerplate project for suit up games"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.5.3"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@1.5.0"
Janitor = "howmanysmall/janitor@1.15.6"
t = "shanebutt/t@1.3.1"
Timer = "sleitnick/timer@1.1.2"
trove = "sleitnick/trove@1.0.1"
GameAnalytics = "dig1t/gameanalytics-sdk@2.2.4"
